$image = /home/Exil/Pictures/wallpaper/river-revine.jpg

$background = rgba(10131aff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2d3038ff)

$inverse_primary = rgba(51651dff)

$inverse_surface = rgba(e0e2ecff)

$on_background = rgba(e0e2ecff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(273500ff)

$on_primary_container = rgba(d3ec94ff)

$on_primary_fixed = rgba(151f00ff)

$on_primary_fixed_variant = rgba(3a4d04ff)

$on_secondary = rgba(43273fff)

$on_secondary_container = rgba(ffd7f4ff)

$on_secondary_fixed = rgba(2c1229ff)

$on_secondary_fixed_variant = rgba(5c3d56ff)

$on_surface = rgba(e0e2ecff)

$on_surface_variant = rgba(c0c6d5ff)

$on_tertiary = rgba(103158ff)

$on_tertiary_container = rgba(d5e3ffff)

$on_tertiary_fixed = rgba(001c3bff)

$on_tertiary_fixed_variant = rgba(2b4770ff)

$outline = rgba(8a919fff)

$outline_variant = rgba(404753ff)

$primary = rgba(b8d07bff)

$primary_container = rgba(3a4d04ff)

$primary_fixed = rgba(d3ec94ff)

$primary_fixed_dim = rgba(b8d07bff)

$scrim = rgba(000000ff)

$secondary = rgba(e4badaff)

$secondary_container = rgba(5c3d56ff)

$secondary_fixed = rgba(ffd7f4ff)

$secondary_fixed_dim = rgba(e4badaff)

$shadow = rgba(000000ff)

$source_color = rgba(18547bff)

$surface = rgba(10131aff)

$surface_bright = rgba(363941ff)

$surface_container = rgba(1c2026ff)

$surface_container_high = rgba(262a31ff)

$surface_container_highest = rgba(31353cff)

$surface_container_low = rgba(181c22ff)

$surface_container_lowest = rgba(0b0e15ff)

$surface_dim = rgba(10131aff)

$surface_tint = rgba(b8d07bff)

$surface_variant = rgba(404753ff)

$tertiary = rgba(acc8f7ff)

$tertiary_container = rgba(2b4770ff)

$tertiary_fixed = rgba(d5e3ffff)

$tertiary_fixed_dim = rgba(acc8f7ff)

