$config = .
source = $config/colors.conf
source = $config/monitor.conf
source = $config/apps.conf
source = $config/envariable.conf
source = $config/style.conf
source = $config/keybinds.conf
source = $config/rule.conf
source = $config/plugins.conf

exec-once = hyprpm reload -n
exec-once = swayidle -w
exec-once = awww-daemon & ~/.config/awww/wallpaper.sh
exec-once = dunst

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# Set dark theme for GTK3/4 apps (including FileZilla)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"   # or your preferred dark GTK theme
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Enable Qt theming
env = QT_QPA_PLATFORMTHEME,qt6ct
