general {
  hide_cursor = true
  ignore_empty_input = true
}

background {
  monitor =
  path = $HOME/.config/background
  blur_passes = 0
  color = rgba(17, 17, 17, 1.0)
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(204, 136, 34, 1.0)
  inner_color = rgba(200, 200, 200, 1.0)
  font_color = rgba(10, 10, 10, 1.0)
  font_family = maple mono nf
  placeholder_text = Input Password
  fade_on_empty = true
  fail_color = rgba(204, 34, 34, 1.0)
  check_color = rgba(204, 136, 34, 1.0)
  position = 0, 0
  halign = center
  valign = center
}

label {
  monitor =
  text = $TIME
  font_size = 90
  font_family = maple mono nf
  color = rgba(255, 255, 255, 1.0)
  position = 0, 150
  halign = center
  valign = center
}
