$config = .
source = $config/hyprland/monitor.conf
source = $config/hyprland/apps.conf
source = $config/hyprland/envariable.conf
source = $config/hyprland/style.conf
source = $config/hyprland/keybinds.conf
source = $config/hyprland/rule.conf
source = $config/hyprland/plugins.conf

exec-once = hyprpm reload -n
exec-once = swayidle -w
exec-once = dunst 

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

