# top row
monitor=DP-9,1920x1080@60,0x0,1
monitor=DP-10,1920x1080@60,1920x0,1

# laptop centered below (main)
monitor=eDP-1,2560x1600@165,1120x1080,1.6

# workspace assignment
workspace=1,monitor:eDP-1
workspace=2,monitor:DP-9
workspace=3,monitor:DP-10

xwayland {force_zero_scaling = true}
